### ISSUE TITLE
ImportError: No module named 'StringIO'

### ISSUE THREAD

**Issue by tseemann** [peterk87/sistr_cmd#1]
```
python3 sistr_cmd.py -i /mnt/seq/MDU/QC/2016-08678/spades.fa -o csv -m

2016-06-16 12:40:04,939 INFO: Initializing temporary analysis directory and preparing for BLAST 
searching. [in sistr_cmd.py:102]
2016-06-16 12:40:04,964 INFO: Temporary FASTA file copied to tmp/spades.fa [in sistr_cmd.py:104]
2016-06-16 12:40:05,791 INFO: Running BLAST on serovar predictive cgMLST330 alleles [in sistr_cmd.py:119]
2016-06-16 12:40:16,781 INFO: Reading BLAST output file "tmp/cgmlst330.fasta-spades.fa-2016Jun16_12_40_05.blast" [in sistr_cmd.py:121]
2016-06-16 12:40:16,867 INFO: Found 39202 cgMLST330 allele BLAST results [in sistr_cmd.py:123]
2016-06-16 12:40:16,869 INFO: Found 328 perfect matches to cgMLST330 alleles [in sistr_cmd.py:125]
2016-06-16 12:40:16,869 INFO: Calculating number of matching alleles to serovar predictive cgMLST330 profiles [in sistr_cmd.py:127]
2016-06-16 12:40:16,910 INFO: Top serovar by cgMLST profile matching: "Typhimurium" with 326 matching alleles, distance=1.2% [in sistr_cmd.py:145]
2016-06-16 12:40:16,910 INFO: Deleting temporary working directory at tmp [in sistr_cmd.py:156]
Traceback (most recent call last):
  File "sistr_cmd.py", line 162, in <module>
    run_mash()
  File "sistr_cmd.py", line 56, in run_mash
    df_mash = mash_output_to_pandas_df(mash_out)
  File "/home/tseemann/tmp/sistr_cmd/src/mash.py", line 39, in mash_output_to_pandas_df
    from StringIO import StringIO
ImportError: No module named 'StringIO'
```

**Comment by peterk87** [comment]
@tseemann Thanks for the heads up on the issues with Python 2 vs 3! No reason not to support both. Let me know if you encounter any other issues.
