### ISSUE TITLE
ERROR when using --no-cgmlst 

### ISSUE THREAD

**Issue by Aron-github** [peterk87/sistr_cmd#19]
Hi,

I was trying out different combos of sistr optional arguments...

When trying:
`sistr --qc -vv --no-cgmlst -f tab -o sistr-output_mytrial.tab my_fasta_Stanley.fasta 2> temp_mytrial.txt`

No output _(sistr-output_mytrial.tab)_ is produced because of the following errors 

> 2017-05-19 11:45:07,881 INFO: Running sistr_cmd 0.3.6 [in /usr/local/lib/python2.7/dist-packages/sistr/sistr_cmd.py:299]
2017-05-19 11:45:07,882 INFO: Serial single threaded run mode on 1 genomes [in /usr/local/lib/python2.7/dist-packages/sistr/sistr_cmd.py:326]
2017-05-19 11:45:07,882 INFO: Initializing temporary analysis directory "/tmp/20170519114507-SISTR-my_fasta_Stanley" and preparing for BLAST searching. [in /usr/local/lib/python2.7/dist-packages/sistr/sistr_cmd.py:185]
2017-05-19 11:45:07,882 INFO: Trying to create analysis directory at: /tmp/20170519114507-SISTR-my_fasta_Stanley [in /usr/local/lib/python2.7/dist-packages/sistr/src/blast_wrapper/__init__.py:45]
2017-05-19 11:45:07,971 INFO: Temporary FASTA file copied to /tmp/20170519114507-SISTR-my_fasta_Stanley/my_fasta_Stanley_fasta [in /usr/local/lib/python2.7/dist-packages/sistr/sistr_cmd.py:187]
2017-05-19 11:45:08,704 INFO: my_fasta_Stanley | Antigen gene BLAST serovar prediction: "Stanley" serogroup=B 1,4,[5],12,[27]:d:1,2 [in /usr/local/lib/python2.7/dist-packages/sistr/sistr_cmd.py:217]
2017-05-19 11:45:08,704 INFO: my_fasta_Stanley | Subspecies prediction: None [in /usr/local/lib/python2.7/dist-packages/sistr/sistr_cmd.py:220]
2017-05-19 11:45:08,704 INFO: my_fasta_Stanley | Overall serovar prediction: Stanley [in /usr/local/lib/python2.7/dist-packages/sistr/sistr_cmd.py:223]
2017-05-19 11:45:08,724 INFO: Genome size=4846851 (within gsize thresholds? True) [in /usr/local/lib/python2.7/dist-packages/sistr/src/qc/__init__.py:13]
2017-05-19 11:45:08,725 INFO: Deleting temporary working directory at /tmp/20170519114507-SISTR-my_fasta_Stanley [in /usr/local/lib/python2.7/dist-packages/sistr/sistr_cmd.py:230]
Traceback (most recent call last):
  File "/usr/local/bin/sistr", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/sistr/sistr_cmd.py", line 327, in main
    outputs = [sistr_predict(input_fasta, genome_name, tmp_dir, keep_tmp, args) for input_fasta, genome_name in zip(input_fastas, genome_names)]
  File "/usr/local/lib/python2.7/dist-packages/sistr/sistr_cmd.py", line 225, in sistr_predict
    qc_status, qc_msgs = qc(blast_runner.tmp_fasta_path, cgmlst_results, prediction)
  File "/usr/local/lib/python2.7/dist-packages/sistr/src/qc/__init__.py", line 17, in qc
    if len(cgmlst_results) == 0:
TypeError: object of type 'NoneType' has no len()

Should I infer that cgmlst is compulsory in order for the command to work properly?

In another case 
`sistr --qc -vv -f tab -o sistr-output_mytrial_2.tab my_fasta_Stanley.fasta 2> temp_mytrial_2.txt`
I had 

- some warnings due to gaps in alleles

- [more than expected] _Recoverd novel allele with gaps (n=0)_ that I don't understand how to correctly interpret...

may this findings support inference of low qual assembly?

Thank you in advance!

**Comment by peterk87** [comment]
Hi, thanks for the bug report!

> Should I infer that cgmlst is compulsory in order for the command to work properly?

No, but it's highly recommended for generating high accuracy serovar predictions. You could use Mash instead to find the closest related Salmonella genomes. But with the core genome MLST (cgMLST) scheme built into sistr-cmd, you also get a prediction for the subspecies that your genome belongs to and the general quality of your genome (are there a lot of core genes missing in your genome?) which may explain strange predictions. 


When running sistr-cmd, you may get some info about cgMLST alleles retrieved from your input genomes. This info can be found in the log (e.g. warnings about gaps in alleles, novel alleles encountered, missing alleles, etc) and can be output along with other information about the cgMLST alleles extracted from your input genomes with the ``-a/--alleles-output`` option, which outputs a JSON format file. 

> may this findings support inference of low qual assembly?

Definitely! We've found that the number of missing or partial cgMLST alleles correlates with the quality of the genome where the more missing cgMLST alleles you have the lower quality your genome is likely to be. 

Hope that helps with making sense of the results you're getting!

**Comment by Aron-github** [comment]
Thanks a lot for your help and precious advices! This definitively will help me interpreting these results.
Cheers,
Eleonora
